#! /usr/bin/env python3


from Mergesort import mergesort
from Quicksort import quicksort
from EmmanuelSonja import *

def main():
  # TODO Make this run all the doctests verbose in other modules
  assert(False)
  

if __name__ == "__main__":
  main()


