#! /usr/bin/env python3

# Hash map, linked list, stack, queue, tree, heaps, tries, graphs
# Quicksort, mergesort
# binary search, DFS, BFS

from Mergesort import mergesort
from Quicksort import quicksort
from EmmanuelSonja import *

def make_array():
  return [ 7, 3, 4, -1, 8, 0, 5, 9, 2]


def main():
  print("mergesort")
  a = make_array()
  print(a)
  b = mergesort(a)
  print(b)
  
  print("quicksort")
  print(a)
  quicksort(a)
  print(a)

  print_output()

if __name__ == "__main__":
  main()


